#!/opt/homebrew/bin/python3
"""
Build script for ED Prescriptions.

Converts source data files into base64-encoded JS files that get loaded
by the browser. Run this after editing any data source file.

Usage:
    python build.py
    python build.py --verbose
"""

from __future__ import annotations

import argparse
import base64
import json
import logging
import sys
from pathlib import Path
from typing import Any, NamedTuple

import prescription_converter as converter

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths & Configuration
# ---------------------------------------------------------------------------

PROJECT_ROOT = (Path(__file__).parent / "..").resolve()
DATA_DIR = PROJECT_ROOT / "data"
JS_DIR = PROJECT_ROOT / "js"


class DataFileEntry(NamedTuple):
    source: Path
    output: Path
    var_name: str


PRESCRIPTION_ENTRY = DataFileEntry(
    source=DATA_DIR / "Prescriptions.xlsx",
    output=JS_DIR / "prescription-data.js",
    var_name="PRESCRIPTION_DATA",
)

JSON_ENTRIES = [
    DataFileEntry(
        source=DATA_DIR / "Locations.json",
        output=JS_DIR / "location-data.js",
        var_name="LOCATION_DATA",
    ),
    DataFileEntry(
        source=DATA_DIR / "AuthorizedProviders.json",
        output=JS_DIR / "provider-data.js",
        var_name="PROVIDER_DATA",
    ),
]


# ---------------------------------------------------------------------------
# JS File Generation
# ---------------------------------------------------------------------------


def write_js_file(output_path: Path, var_name: str, data: Any) -> bool:
    """Write data as a base64-encoded JS variable, atomically."""
    try:
        json_bytes = json.dumps(data, separators=(",", ":")).encode("utf-8")
        encoded = base64.b64encode(json_bytes).decode("ascii")
        content = (
            f"// Auto-generated by build.py - do not edit\n"
            f"const {var_name}=JSON.parse(atob(\"{encoded}\"));\n"
        )
        converter.write_file_atomically(output_path, content, suffix=".js")
        logger.info("  Wrote %s (%d bytes encoded)", output_path.name, len(encoded))
        return True
    except Exception as e:
        logger.error("  Error writing %s: %s", output_path.name, e)
        return False


# ---------------------------------------------------------------------------
# Build Steps
# ---------------------------------------------------------------------------


def build_prescriptions(entry: DataFileEntry) -> bool:
    """Convert Excel prescriptions to JS data file."""
    logger.info("Building prescription data...")
    data = converter.convert_excel(entry.source)
    if data is None:
        return False
    return write_js_file(entry.output, entry.var_name, data)


def build_json_file(entry: DataFileEntry) -> bool:
    """Convert a JSON source file to a JS data file."""
    logger.info("Building %s...", entry.output.name)
    try:
        with open(entry.source, "r", encoding="utf-8") as f:
            data = json.load(f)
        return write_js_file(entry.output, entry.var_name, data)
    except FileNotFoundError:
        logger.error("  Source file not found: %s", entry.source)
        return False
    except json.JSONDecodeError as e:
        logger.error("  Invalid JSON in %s: %s", entry.source, e)
        return False


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Build JS data files for ED Prescriptions.",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose debug logging",
    )
    return parser.parse_args()


def main() -> int:
    """Build all data files. Returns 0 on success, 1 on failure."""
    args = parse_args()
    converter.setup_logging(verbose=args.verbose)

    logger.info("=" * 60)
    logger.info("BUILDING DATA FILES")
    logger.info("=" * 60)

    success = build_prescriptions(PRESCRIPTION_ENTRY)

    for entry in JSON_ENTRIES:
        if not build_json_file(entry):
            success = False

    logger.info("=" * 60)
    if success:
        logger.info("BUILD COMPLETE - all data files generated")
    else:
        logger.error("BUILD FAILED - see errors above")
    logger.info("=" * 60)

    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
